### ISSUE TITLE
How to user setting based on auth

### ISSUE THREAD

**Issue by wasiqaftab** [qcod/laravel-app-settings#11]
HI

First of all very nice package. Can you please guide me if i need to add user_id with it so setting will be based upon user whats the best way to achieve it. @saqueib you help will really be appreciated.

** Also what ever i have saved in database when i come back to settings page i cant see it

Thanks alot

**Comment by saqueib** [comment]
You can find the doc here https://github.com/qcod/laravel-app-settings#use-group-setting
