### ISSUE TITLE
seetingUI

### ISSUE THREAD

**Issue by daniellord32** [qcod/laravel-app-settings#12]
possibility I have done something wrong but doing a fresh composer pull and following your guide, Whilst I know hte problem I can't seem to rectify locally.

http://prntscr.com/nse8om

Undefined variable: settingsUI (View: C:\xampp\htdocs\appealsLite\vendor\qcod\laravel-app-settings\src\resources\views\_settings.blade.php)

**Comment by mitajunior** [comment]
@daniellord32 if you are extending the package in your controller please make sure you follow https://github.com/qcod/laravel-app-settings#using-different-controller

``Route::get('your-settings-url', 'SettingsController@index')``
