### ISSUE TITLE
If setting equals

### ISSUE THREAD

**Issue by stublackett** [qcod/laravel-app-settings#16]
Hi, 

Great Laravel package.

Just wondering if there's the ability to show / hide some sections based on a setting.

So for example, I have a section titled "Template Settings" would like to only show this section, if a field titled "Demo" is set to true?

**Comment by saqueib** [comment]
The best way I think you can do it by adding a [custom field type](https://github.com/qcod/laravel-app-settings#custom-input-type).

With the help of some javascript, you should be able to archive it
