### ISSUE TITLE
ENV Override 

### ISSUE THREAD

**Issue by LadyDeathKZN** [qcod/laravel-app-settings#17]
Hi there, I was wondering if you have a way to override env settings with your plugin? I have tried numerous ways but in vain. I don't want my client to have to change the env for mail settings for example, but when I use the method it still pulls it from the ENV file. Do you perhaps have detailed documentation for this?

**Comment by saqueib** [comment]
I would say apply these email settings in AppServiceProvider@boot method

```php
/**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Config::set('mail.from.address', setting('email'));
        Config::set('mail.from.name', setting('from_email_name'))
    }
```
try this and let me know

**Comment by LadyDeathKZN** [comment]
Thank you for the above it works 100%
