### ISSUE TITLE
Class 'Arr' not found

### ISSUE THREAD

**Issue by LadyDeathKZN** [qcod/laravel-app-settings#18]
Hi,

I have followed your instructions to setup the package on laravel. I am getting a Class 'Arr' not found error when trying to access the url. I tried another project and also got the same error

**Comment by LadyDeathKZN** [comment]
Added:
'Arr' => Illuminate\Support\Arr::class,
'Str' => Illuminate\Support\Str::class,

to config/app.php

**Comment by devellopah** [comment]
> Added: 'Arr' => Illuminate\Support\Arr::class, 'Str' => Illuminate\Support\Str::class,
> 
> to config/app.php

The solution made my day. Should be added to repo readme.
