### ISSUE TITLE
Forced to Bootstrap only. Need manual edit on several places for Bulma CSS

### ISSUE THREAD

**Issue by andresmrg** [qcod/laravel-app-settings#19]
You are forcing the CSS with Bootstrap. However, you should add more settings for the form, more classes should be edited from the config. I have to manually change the classes for Bulma CSS framework and remove any bootstrap to make it to work which increases the amount of work. It should be an easy implementation.

Also, it does not support password type input.

**Comment by saqueib** [comment]
Sorry for the late response, but you can configure all the classes from the config file and you are free to [add any new field type](https://github.com/qcod/laravel-app-settings#custom-input-type) needed
