### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by yurirnascimento** [qcod/laravel-app-settings#24]
Hi,

Please, update support to Laravel 7.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for qcod/laravel-app-settings ^1.2 -> satisfiable by qcod/laravel-app-settings[1.2.0].
    - Conclusion: remove laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.4
    - qcod/laravel-app-settings 1.2.0 requires laravel/framework ~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0|^6.0 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.0.4].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.0.4].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.0.4].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.0.4].
    - Can only install one of: laravel/framework[6.x-dev, v7.0.4].
    - Can only install one of: laravel/framework[5.4.x-dev, v7.0.4].
    - Installation request for laravel/framework (locked at v7.0.4, required as ^7.0) -> satisfiable by laravel/framework[v7.0.4].

**Comment by darkperis** [comment]
Laravel 7 support please!

**Comment by yurirnascimento** [comment]
Fixed
