### ISSUE TITLE
php8 version 

### ISSUE THREAD

**Issue by 2618094** [qcod/laravel-app-settings#33]
Pls add support for php8, i hope, all your dependencies already made this :)

**Comment by lordz123** [comment]
no support in php8 ?

**Comment by darkperis** [comment]
Please add php 8 support. Thanks!

**Comment by darkponyhq** [comment]
Laravel 9 is coming, requiring min PHP 8, is it possible to fix the PHP 8 issue? Thanks!

**Comment by AngusDV** [comment]
Use my package 
https://github.com/AngusDV/laravel-setting

**Comment by saqueib** [comment]
Laravel 9 supported now
