### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by rahulmanek** [qcod/laravel-app-settings#40]
When I run `composer require qcod/laravel-app-settings` it shows the following error. I am using laravel 8

> **Your requirements could not be resolved to an installable set of packages.**
> Problem 1
>     - qcod/laravel-app-settings 1.1.0 requires laravel/framework ~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> found laravel/framework[v5.4.0, ..., 
> 5.8.x-dev] but it conflicts with your root composer.json require (^8.12).
>     - qcod/laravel-app-settings[1.2.0, ..., 1.4.0] require php ^7.2 -> your php version (8.0.8) does not satisfy that requirement.
>     - Root composer.json requires qcod/laravel-app-settings ^1.1 -> satisfiable by qcod/laravel-app-settings[1.1.0, 1.2.0, 1.3.0, 1.4.0].

**Comment by saqueib** [comment]
try it now, its now supports php 8
