### ISSUE TITLE
Wheres The Migration?

### ISSUE THREAD

**Issue by HDVinnie** [qcod/laravel-app-settings#6]
README mentions running migration but I don't see a migration file anywhere.

**Comment by saqueib** [comment]
Migration is already loaded through service provider, so if you run php artisan migrate it will create settings table

**Comment by HDVinnie** [comment]
I see thanks.

**Comment by ametad** [comment]
May I suggest the migration file also be published? I make use of a multi-tenant solution in which multiple sets of migrations are, each for a different scenario. In short, this migration needs in a custom db connection.

**Comment by ClausMunch** [comment]
> May I suggest the migration file also be published? I make use of a multi-tenant solution in which multiple sets of migrations are, each for a different scenario. In short, this migration needs in a custom db connection.

This could be really helpfull! :)
